import React,{useEffect,useRef,useState} from "react";
import {Home,BookOpen,Dumbbell,FolderKanban,User,ChevronLeft,ChevronRight,Play,Lock,CheckCircle2,Flame,Bot,Send,Loader2} from "lucide-react";
const BACKEND_URL="https://YOUR-BACKEND-URL.vercel.app";
const UI={en:{tagline:"Learn · Code · Build Your Future",getStarted:"Get Started",home:"Home",learn:"Learn",practice:"Practice",projects:"Projects",profile:"Profile",hiLearner:"Hi Learner! 👋",keepGrowing:"Keep learning, keep growing!",yourProgress:"Your Progress",lessons:"Lessons",xp:"XP",streak:"Day Streak",coursePath:"Course Path",comingSoon:"Coming Soon",locked:"Locked",part:"Part",next:"Next",previous:"Previous",runCode:"Run",output:"Output:",quizTime:"Quiz Time!",correct:"Correct! 🎉",incorrect:"Not quite — try again",finishLesson:"Finish & Claim XP",aiTutor:"AI Tutor",askAnything:"Ask anything about this lesson!",typeQuestion:"Type your question...",thinking:"Thinking...",settings:"Settings",chooseLanguage:"Choose Language",back:"Back",score:"Score",codePlayground:"Code Playground",projectDetails:"Project Details",difficulty:"Difficulty",skills:"Skills you'll use",passToUnlock:"Pass the quiz to complete this lesson."},hi:{tagline:"सीखो · कोड करो · अपना भविष्य बनाओ",getStarted:"शुरू करें",home:"होम",learn:"सीखें",practice:"अभ्यास",projects:"प्रोजेक्ट्स",profile:"प्रोफाइल",hiLearner:"नमस्ते Learner! 👋",keepGrowing:"सीखते रहो, बढ़ते रहो!",yourProgress:"आपकी प्रगति",lessons:"पाठ",xp:"XP",streak:"दिन स्ट्रीक",coursePath:"कोर्स पाथ",comingSoon:"जल्द आ रहा है",locked:"लॉक्ड",part:"भाग",next:"आगे",previous:"पीछे",runCode:"रन करें",output:"आउटपुट:",quizTime:"क्विज़ टाइम!",correct:"सही जवाब! 🎉",incorrect:"गलत — फिर से कोशिश करें",finishLesson:"पूरा करें और XP लें",aiTutor:"AI ट्यूटर",askAnything:"इस lesson के बारे में कुछ भी पूछें!",typeQuestion:"अपना सवाल लिखें...",thinking:"सोच रहा हूँ...",settings:"सेटिंग्स",chooseLanguage:"भाषा चुनें",back:"वापस",score:"स्कोर",codePlayground:"कोड प्लेग्राउंड",projectDetails:"प्रोजेक्ट विवरण",difficulty:"कठिनाई",skills:"इस्तेमाल होने वाले skills",passToUnlock:"इस lesson को पूरा करने के लिए quiz pass करें."},es:{tagline:"Aprende · Programa · Construye tu Futuro",getStarted:"Comenzar",home:"Inicio",learn:"Aprender",practice:"Práctica",projects:"Proyectos",profile:"Perfil",hiLearner:"¡Hola, Estudiante! 👋",keepGrowing:"¡Sigue aprendiendo, sigue creciendo!",yourProgress:"Tu Progreso",lessons:"Lecciones",xp:"XP",streak:"Días seguidos",coursePath:"Ruta del Curso",comingSoon:"Próximamente",locked:"Bloqueado",part:"Parte",next:"Siguiente",previous:"Anterior",runCode:"Ejecutar",output:"Salida:",quizTime:"¡Hora del Quiz!",correct:"¡Correcto! 🎉",incorrect:"No es correcto — intenta de nuevo",finishLesson:"Terminar y Reclamar XP",aiTutor:"Tutor IA",askAnything:"¡Pregunta lo que quieras sobre esta lección!",typeQuestion:"Escribe tu pregunta...",thinking:"Pensando...",settings:"Ajustes",chooseLanguage:"Elige Idioma",back:"Atrás",score:"Puntaje",codePlayground:"Zona de Código",projectDetails:"Detalles del Proyecto",difficulty:"Dificultad",skills:"Habilidades a usar",passToUnlock:"Aprueba el quiz para completar esta lección."}};
const LANG=[{code:"en",label:"English",flag:"🇺🇸"},{code:"hi",label:"हिन्दी",flag:"🇮🇳"},{code:"es",label:"Español",flag:"🇪🇸"}];
const MODULES=[{id:1,icon:"🐍",color:"from-pink-500 to-rose-500",lessonsCount:12,name:{en:"Python Introduction",hi:"Python परिचय",es:"Introducción a Python"}},{id:2,icon:"💻",color:"from-sky-500 to-blue-500",lessonsCount:8,name:{en:"Setup & Installation",hi:"सेटअप और इंस्टॉलेशन",es:"Instalación"}},{id:3,icon:"🔷",color:"from-amber-400 to-orange-500",lessonsCount:15,real:"var1",name:{en:"Variables & Data Types",hi:"Variables और Data Types",es:"Variables y Tipos de Datos"}},{id:4,icon:"🧩",color:"from-amber-500 to-yellow-400",lessonsCount:10,name:{en:"Operators",hi:"ऑपरेटर्स",es:"Operadores"}},{id:5,icon:"🔀",color:"from-violet-500 to-purple-500",lessonsCount:14,name:{en:"Conditions",hi:"कंडीशन्स",es:"Condiciones"}},{id:6,icon:"🔁",color:"from-emerald-500 to-teal-500",lessonsCount:16,real:"loop1",name:{en:"Loops",hi:"लूप्स",es:"Bucles"}},{id:7,icon:"⚙️",color:"from-amber-400 to-orange-400",lessonsCount:15,name:{en:"Functions",hi:"फंक्शन्स",es:"Funciones"}},{id:8,icon:"📦",color:"from-pink-500 to-fuchsia-500",lessonsCount:9,name:{en:"Modules & Packages",hi:"मॉड्यूल्स और पैकेजेस",es:"Módulos"}}];
const LESSONS={var1:{title:"What is a Variable?",parts:[{h:"The Idea",b:"A variable is a labeled box where you store a value in memory, so you can use it later by name."},{h:"Creating a Variable",b:"In Python, write a name, an equals sign, and a value.",c:'name = "Arjun"\nage = 20\ncity = "Delhi"'},{h:"Different Types",b:"Variables can hold text, whole numbers, decimals, or True/False.",c:'price = 49.99\nis_open = True\nprint(price, is_open)'},{h:"Try It Yourself",b:"Change the values and press Run.",c:'favorite_lang = "Python"\nprint("I love", favorite_lang)'}],quiz:[{q:"How do you create a variable in Python?",o:["var x = 10","x = 10","int x = 10","x := 10"],a:1},{q:"What type is age = 20?",o:["string","int","float","boolean"],a:1}]},loop1:{title:"For Loops",parts:[{h:"Why Loops?",b:"A loop repeats an action many times without copy-pasting code."},{h:"The for Loop",b:"range(5) gives 0,1,2,3,4.",c:'for i in range(5):\n    print(i)'},{h:"Looping with a Message",b:"Use print() inside a loop to repeat a message.",c:'for i in range(3):\n    print("Count:", i)'},{h:"Try It Yourself",b:"Change the range number and Run it.",c:'for i in range(4):\n    print("Hello", i)'}],quiz:[{q:"How many times does range(5) loop?",o:["4","5","6","Infinite"],a:1},{q:"Which keyword starts a for loop?",o:["loop","for","repeat","foreach"],a:1}]}};
function run(code){const vars={},out=[];const val=x=>{x=x.trim();if((x.startsWith('"')&&x.endsWith('"'))||(x.startsWith("'")&&x.endsWith("'")))return x.slice(1,-1);if(x==="True")return true;if(x==="False")return false;if(x in vars)return vars[x];if(x!==""&&!isNaN(x))return Number(x);return x};const print=x=>out.push(x.split(",").map(val).join(" "));const lines=code.split("\n");for(let i=0;i<lines.length;i++){let l=lines[i].trim(),m=l.match(/^for\s+(\w+)\s+in\s+range\((\d+)\):$/);if(m){let j=i+1,body=[];while(j<lines.length&&/^\s+/.test(lines[j]))body.push(lines[j].trim()),j++;for(let k=0;k<+m[2];k++){vars[m[1]]=k;body.forEach(x=>{let p=x.match(/^print\((.*)\)$/);if(p)print(p[1])})}i=j-1}else{let p=l.match(/^print\((.*)\)$/),a=l.match(/^(\w+)\s*=\s*(.+)$/);if(p)print(p[1]);else if(a)vars[a[1]]=val(a[2])}}return out.length?out:["(no output)"]}
function Header({title,back}){return <div className="flex items-center justify-between px-4 pt-3 pb-2"><button onClick={back} className="p-1 text-white/80"><ChevronLeft size={22}/></button><h1 className="text-white font-semibold text-base truncate">{title}</h1><div className="w-6"/></div>}
function Nav({screen,setScreen,t}){return <div className="flex justify-around border-t border-white/10 bg-slate-950/90 py-2">{[["home",t.home,Home],["course",t.learn,BookOpen],["quiz",t.practice,Dumbbell],["projects",t.projects,FolderKanban],["settings",t.profile,User]].map(([k,l,I])=><button key={k} onClick={()=>setScreen(k)} className={`flex flex-col items-center text-[10px] ${screen===k?'text-sky-400':'text-slate-500'}`}><I size={20}/>{l}</button>)}</div>}
function HomeScreen({go,t,p}){return <div className="h-full overflow-y-auto bg-slate-950 px-4 pt-4"><div className="flex justify-between mb-4"><div><b className="text-white">{t.hiLearner}</b><p className="text-slate-400 text-xs">{t.keepGrowing}</p></div><span className="text-orange-300 text-xs"><Flame size={14} className="inline"/> {p.streak}</span></div><div className="bg-gradient-to-r from-violet-700 to-sky-600 rounded-2xl p-4 mb-4"><p className="text-white/80 text-xs">{t.yourProgress}</p><b className="text-white text-lg">{p.completed.length} / 2 {t.lessons}</b><p className="text-white/70 text-xs">{p.xp} XP</p></div><b className="text-white">{t.coursePath}</b><div className="space-y-2 mt-2">{MODULES.filter(m=>m.real).map(m=><button key={m.id} onClick={()=>go(m.real)} className="w-full flex items-center gap-3 bg-slate-900 border border-white/10 rounded-xl p-3"><span className={`w-10 h-10 rounded-xl bg-gradient-to-br ${m.color} flex items-center justify-center`}>{m.icon}</span><span className="flex-1 text-left text-white text-sm">{m.name[t._lang]}<small className="block text-slate-400">{LESSONS[m.real].title}</small></span><ChevronRight size={18} className="text-slate-500"/></button>)}</div><button onClick={()=>go("tutor")} className="w-full mt-4 flex gap-2 bg-slate-900 border border-sky-500/40 rounded-xl p-3 text-white text-sm"><Bot size={20} className="text-sky-400"/> {t.aiTutor} →</button></div>}
function Course({go,t,p}){return <div className="h-full flex flex-col bg-slate-950"><Header title={t.coursePath} back={()=>go('home')}/><div className="flex-1 overflow-y-auto px-4 space-y-2">{MODULES.map(m=><button key={m.id} disabled={!m.real} onClick={()=>m.real&&go(m.real)} className={`w-full flex gap-3 p-3 rounded-xl border border-white/10 ${m.real?'bg-slate-900':'bg-slate-900/50 opacity-60'}`}><span className={`w-10 h-10 rounded-xl bg-gradient-to-br ${m.color} flex items-center justify-center`}>{m.icon}</span><span className="flex-1 text-left text-white text-sm">{m.id}. {m.name[t._lang]}<small className="block text-slate-400">{m.lessonsCount} {t.lessons} {!m.real&&'· '+t.comingSoon}</small></span>{m.real?<ChevronRight size={18}/>:<Lock size={16}/>}</button>)}</div></div>}
function Lesson({go,t,id,complete}){const [i,setI]=useState(0),[quiz,setQuiz]=useState(false),[code,setCode]=useState(''),[out,setOut]=useState(null);const l=LESSONS[id];useEffect(()=>{setCode(l.parts[i].c||'');setOut(null)},[i,id]);if(quiz)return <Quiz t={t} data={l.quiz} done={()=>{complete(id);go('home')}} back={()=>setQuiz(false)}/>;const part=l.parts[i];return <div className="h-full flex flex-col bg-slate-950"><Header title={l.title} back={()=>go('course')}/><div className="flex-1 overflow-y-auto px-4"><div className="flex gap-1 my-3">{l.parts.map((_,x)=><div className={`h-1.5 flex-1 rounded ${x<=i?'bg-sky-400':'bg-slate-800'}`}/>)}</div><p className="text-slate-500 text-xs">{t.part} {i+1}/4</p><h2 className="text-white font-bold text-lg mt-1">{part.h}</h2><p className="text-slate-300 text-sm mt-2">{part.b}</p>{part.c&&<><p className="text-slate-400 text-xs mt-4">{t.codePlayground}</p><textarea value={code} onChange={e=>setCode(e.target.value)} rows="5" className="w-full mt-1 bg-slate-900 text-emerald-400 font-mono text-xs p-3 rounded-xl"/><button onClick={()=>setOut(run(code))} className="mt-2 bg-gradient-to-r from-violet-600 to-sky-500 text-white px-4 py-2 rounded-lg text-sm flex gap-2"><Play size={16}/>{t.runCode}</button>{out&&<div className="bg-slate-900 p-3 mt-2 rounded-xl text-emerald-400 font-mono text-xs">{out.map(x=><div>{x}</div>)}</div>}</>}</div><div className="flex justify-between p-3 border-t border-white/10"><button disabled={!i} onClick={()=>setI(i-1)} className="text-slate-300">{t.previous}</button><button onClick={()=>i<3?setI(i+1):setQuiz(true)} className="bg-gradient-to-r from-violet-600 to-sky-500 text-white px-5 py-2 rounded-lg">{i<3?t.next:t.quizTime}</button></div></div>}
function Quiz({t,data,done,back}){const [i,setI]=useState(0),[sel,setSel]=useState(null),[score,setScore]=useState(0);const q=data[i];const choose=x=>{if(sel!==null)return;setSel(x);if(x===q.a)setScore(s=>s+1)};return <div className="h-full bg-slate-950"><Header title={t.quizTime} back={back}/><div className="px-4"><p className="text-slate-500 text-xs mb-2">{t.passToUnlock}</p><div className="bg-slate-900 p-4 rounded-2xl"><p className="text-white mb-4">{q.q}</p>{q.o.map((x,j)=><button onClick={()=>choose(j)} className={`w-full text-left p-3 mb-2 rounded-lg border ${sel===null?'bg-slate-800 border-white/10 text-slate-200':j===q.a?'bg-emerald-500/20 border-emerald-400 text-emerald-300':sel===j?'bg-rose-500/20 border-rose-400 text-rose-300':'bg-slate-800 border-white/10 text-slate-300'}`}>{x}</button>)}{sel!==null&&<button onClick={()=>i+1<data.length?(setI(i+1),setSel(null)):done()} className="w-full bg-gradient-to-r from-violet-600 to-sky-500 text-white py-2 rounded-lg">{i+1<data.length?t.next:t.finishLesson}</button>}</div><p className="text-slate-500 text-xs text-center mt-3">{t.score}: {score}/{data.length}</p></div></div>}
function Tutor({go,t,lang}){const [msgs,setMsgs]=useState([{bot:1,text:t.askAnything}]),[input,setInput]=useState(''),[loading,setLoading]=useState(false),end=useRef();useEffect(()=>end.current?.scrollIntoView({behavior:'smooth'}),[msgs]);async function send(){if(!input.trim()||loading)return;const text=input;setInput('');const next=[...msgs,{bot:0,text}];setMsgs(next);setLoading(true);try{const r=await fetch(`${BACKEND_URL}/api/tutor`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({system:`You are a friendly Python tutor. Reply in ${lang==='hi'?'Hindi/Hinglish':lang==='es'?'Spanish':'English'}, under 80 words.`,messages:next.map(m=>({role:m.bot?'assistant':'user',content:m.text}))})});const d=await r.json();setMsgs(m=>[...m,{bot:1,text:(d.content||[]).map(c=>c.text||'').join('\n')||'Sorry, no response.'}])}catch(e){setMsgs(m=>[...m,{bot:1,text:'Network error — please try again.'}])}finally{setLoading(false)}}return <div className="h-full flex flex-col bg-slate-950"><Header title={t.aiTutor} back={()=>go('home')}/><div className="flex-1 overflow-y-auto px-4 space-y-2">{msgs.map((m,i)=><div key={i} className={`max-w-[85%] p-3 rounded-xl text-sm ${m.bot?'bg-slate-900 text-slate-200':'bg-sky-600 text-white ml-auto'}`}>{m.text}</div>)}{loading&&<Loader2 className="animate-spin text-slate-400" size={16}/>}<div ref={end}/></div><div className="p-3 border-t border-white/10 flex gap-2"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder={t.typeQuestion} className="flex-1 bg-slate-900 text-white rounded-full px-4 py-2"/><button onClick={send} className="bg-sky-600 p-2 rounded-full text-white"><Send size={16}/></button></div></div>}
function Settings({go,t,lang,setLang}){return <div className="h-full bg-slate-950"><Header title={t.settings} back={()=>go('home')}/><div className="px-4"><p className="text-slate-400 text-xs mb-2">{t.chooseLanguage}</p>{LANG.map(x=><button key={x.code} onClick={()=>setLang(x.code)} className={`w-full p-3 mb-2 rounded-xl border flex gap-3 text-white ${lang===x.code?'border-sky-400':'border-white/10 bg-slate-900'}`}>{x.flag} {x.label}{lang===x.code&&<CheckCircle2 className="ml-auto text-sky-400" size={18}/>}</button>)}</div></div>}
function Projects({go,t}){const ps=[['🧮','Calculator','Beginner'],['✅','To-Do App','Beginner'],['⛅','Weather App','Intermediate'],['🤖','Chat Bot','Intermediate'],['🐍','Snake Game','Advanced'],['📊','Data Visualizer','Advanced']];return <div className="h-full bg-slate-950"><Header title={t.projects} back={()=>go('home')}/><div className="grid grid-cols-2 gap-3 p-4">{{ps.map(p=><button onClick={()=>alert(`${p[1]} project selected`)}className="bg-slate-900 border border-white/10 rounded-xl p-3 text-left"><span className="text-2xl">{p[0]}</span><p className="text-white text-sm">{p[1]}</p><p className="text-slate-400 text-xs">{p[2]}</p></button>)}</div></div>}
export default function PythonNexusApp(){let content =
  screen === 'home'
    ? <HomeScreen go={go} t={t} p={p}/>
    : screen === 'course'
    ? <Course go={go} t={t} p={p}/>
    : screen === 'quiz'
    ? <Course go={go} t={t} p={p}/>
    : LESSONS[screen]
    ? <Lesson go={go} t={t} id={screen} complete={complete}/>
    : screen === 'tutor'
    ? <Tutor go={go} t={t} lang={lang}/>
    : screen === 'projects'
    ? <Projects go={go} t={t}/>
    : <Settings go={go} t={t} lang={lang} setLang={change}/>;
